Update check-changelog.yml

diff --git a/.github/workflows/check-changelog.yml b/.github/workflows/check-changelog.yml
--- a/.github/workflows/check-changelog.yml
+++ b/.github/workflows/check-changelog.yml
@@ -1,19 +1,30 @@
-
-name: Validar archivo changelog.md
-
+name: Validar Changelog
 
 on:
   pull_request:
-
+    paths:
+      - 'docs/changelog.md'
+      
 jobs:
   validar-changelog:
     runs-on: ubuntu-latest
+
     steps:
-      - name: Verificar si changelog.md fue modificado
-        run: |
-          if git diff --no-index --name-only origin/${{ github.base_ref }}..${{ github.head_ref }} | grep -q 'changelog.md'; then
-            echo "::success::El archivo changelog.md fue modificado en el PR."
-          else
-            echo "::error::El archivo changelog.md no ha sido modificado en el PR."
-            exit 1
-          fi
+    - name: Checkout código
+      uses: actions/checkout@v2
+
+    - name: Validar existencia de changelog.md
+      run: |
+        if [ ! -f docs/changelog.md ]; then
+          echo "Error: El archivo changelog.md no existe en la carpeta docs."
+          exit 1
+        fi
+
+    - name: Validar cambios en changelog.md
+      run: |
+        if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '^docs/changelog.md$'; then
+          echo "Changelog.md modificado en el Pull Request."
+        else
+          echo "Error: No se ha modificado changelog.md en el Pull Request."
+          exit 1
+        fi
